name: Test deployment

on:
  pull_request:

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - name: Run Tutorials Script
        run: |
          chmod +x tutorials-script.sh
          ./tutorials-script.sh
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: sh ./vue-docs.sh
